### ISSUE TITLE
`LiteXL:is_installed`/`Bottle:is_constructed` don't check if the executable is in place in the bottle

### ISSUE THREAD

**Issue by Guldoman** [lite-xl/lite-xl-plugin-manager#40]
`LiteXL:is_installed` and/or `Bottle:is_constructed` should check that the `lite-xl` executable is present in the bottle.

If a bottle creation fails, the next time it's "used", lpm will fail with:
```sh
sh: line 1: .../.config/lite-xl/lpm/bottles/93fb07a5108b70c58ca61f755944bb4c2bf5050df9cb4bcb9e1ba034ab2e9805/lite-xl: No such file or directory
```

**Comment by adamharrison** [comment]
Yeah, bottle creation should be started in the tmp folder, rather than in the primary folder, and then move it atomically. That's how I'm doing it elsewhere, and is just generally a better pattern. Will look into it.

**Comment by adamharrison** [comment]
Try 76f68d2c61c8619948c7a1a33536a1bdff69fd3f. Should fix it.

**Comment by Guldoman** [comment]
That might solve the situation where the bottle fails construction, but still fails to rebuild it if the content of the bottle (and not the bottle dir itself) is deleted.

But then the problem is on the user that broke the bottle so it might not be a real issue anymore.
Maybe just a better error message when the executable is not there would be enough.
